using Newtonsoft.Json;
using Pulsar4X.Interfaces;
using Pulsar4X.Components;
using Pulsar4X.Engine;
using Pulsar4X.Datablobs;

namespace Pulsar4X.GroundCombat
{
    /// <summary>
    /// ENVIRONMENTAL HARDENING — the second surface-hazard armour, the twin of <see cref="GroundSealAtb"/> (Sealed
    /// Systems). Where the seal lets a unit survive an airless rock (Vacuum) or a poison sky (ToxicAtmosphere), HARDENING
    /// lets it survive the two DAMAGING surface storms an unsealed AND a sealed unit both die to today: a scorching /
    /// freezing world (fire tornadoes / cryostorms = <c>HeatDamage</c>) and a corrosive superstorm
    /// (<c>CorrosiveDamage</c>). It is the kit the planet-view study found MISSING — a fully sealed marine still burned on
    /// Venus (≈23/hr fire) and froze on Ganymede, because the seal covers only Vacuum + Toxic. This closes the
    /// "you can't hold this world without the right KIT" decision: the seal is the price of admission to a vacuum/toxic
    /// world; hardening is the price of admission to a burning/freezing/corrosive one.
    ///
    /// It is a COMPONENT (CONVENTIONS §6) mounted in the Entity Assembler onto a ground chassis — NOT a bespoke
    /// "hardened unit" type (GroundCombat/CLAUDE.md LOCKED PRINCIPLE): the hardened ROLE EMERGES from the part, so it is
    /// researched / built / mounted / lost like any gear, and shooting the hardening off ends the protection (the grave
    /// rung). Like the seal it is INERT on install — the assembler (<see cref="GroundUnitAssembly.Compute"/>) reads the
    /// BEST mounted hardening's <see cref="Hardening"/> and writes it into the design's
    /// <see cref="GroundUnitDesign.EnvironmentalResistance"/> map (keyed by HeatDamage + CorrosiveDamage) at build time,
    /// so install/uninstall are no-ops; it is NEVER read in combat.
    ///
    /// <see cref="Hardening"/> is the ONE dial (CONVENTIONS §16): the fraction of the two damaging surface hazards'
    /// attrition negated, 0..1. One dial covers BOTH HeatDamage and CorrosiveDamage — a ruggedised envelope that shrugs
    /// off thermal extremes also resists chemical burn (the developer's call, paralleling "sealing is sealing"). NOTE:
    /// HeatDamage is the engine's thermal effect for BOTH fire (hot) and cryo (cold), so one dial hardens against fire
    /// AND cryo. Fire + corrosive are generated by <c>PlanetEnvironmentFactory</c> today; a cold-world cryo hazard is a
    /// flagged follow-up on the GENERATOR side (this component already resists it the moment one is generated). Single
    /// double-arg ctor for the JSON/NCalc binder — the binder is EXACT-ARITY (GroundCombat/CLAUDE.md gotcha 6), so the
    /// base-mod template feeds exactly one AtbConstrArgs value. Never throws (L4).
    /// </summary>
    public class GroundHardeningAtb : BaseDataBlob, IComponentDesignAttribute
    {
        /// <summary>The fraction of HeatDamage (fire/cryo) + CorrosiveDamage attrition this hardening negates (clamped
        /// 0..1; 0 = an unhardened design that protects nothing, 1 = fully hardened, immune to both). Read at assembly,
        /// folded into the design's <see cref="GroundUnitDesign.EnvironmentalResistance"/> map; never read by the combat
        /// resolver.</summary>
        [JsonProperty] public double Hardening { get; internal set; }   // 0..1 fraction of thermal/corrosive attrition negated

        public GroundHardeningAtb() { }

        // ONE double arg for the JSON/NCalc binder (gotcha 6): the base-mod template feeds a SINGLE
        // AtbConstrArgs(PropertyValue('Hardening')) value, so the ctor takes exactly one, matching arity.
        public GroundHardeningAtb(double hardening)
        {
            Hardening = hardening < 0 ? 0 : (hardening > 1 ? 1 : hardening);
        }

        public override object Clone() => new GroundHardeningAtb(Hardening);

        public void OnComponentInstallation(Entity parentEntity, ComponentInstance componentInstance) { }
        public void OnComponentUninstallation(Entity parentEntity, ComponentInstance componentInstance) { }

        public string AtbName() => "Environmental Hardening";
        public string AtbDescription()
            => $"Thermal + corrosion hardening — lets this unit survive a burning/freezing world (fire tornadoes, cryostorms) or a corrosive superstorm, negating {Hardening:P0} of that surface attrition. The seal keeps a unit alive in vacuum/toxic air; this keeps it alive on the worlds that would otherwise cook, freeze, or dissolve even a sealed suit. The harder the shell, the dearer the unit to field.";
    }
}
